[package]
name = "motor"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
esp-idf-sys = { workspace = true }
esp-idf-hal = { workspace = true }
log = { workspace = true }
